# Generated by Django 4.2.3 on 2023-07-22 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='patient name')),
                ('phone', models.CharField(max_length=14, verbose_name='phone number')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('address_number', models.CharField(max_length=100, verbose_name='address number')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
