# Generated by Django 4.2.3 on 2023-07-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='phone number'),
        ),
    ]
